In [105]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os
df = pd.read_csv('data_iris.csv',header='infer')
print(df.shape)
df.head(3)

(150, 5)


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [ ]:
x = df['Petal.Length']
y = df['Sepal.Length']

In [41]:
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [35]:
x.corr(y)

0.8717537758865831

In [61]:
df1 = df.copy()
df1.Species.replace({
    'setosa': 0,
    'versicolor': 1,
    'virginica': 2,
}, inplace=True)
np.round(df1.corr(),3)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_10644\4180225168.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1.Species.replace({
C:\Users\Administrator\AppData\Local\Temp\ipykernel_10644\4180225168.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.Species.replace({


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
Sepal.Length         1.000       -0.118         0.872        0.818    0.783
Sepal.Width         -0.118        1.000        -0.428       -0.366   -0.427
Petal.Length         0.872       -0.428         1.000        0.963    0.949
Petal.Width          0.818       -0.366         0.963        1.000    0.957
Species              0.783       -0.427         0.949        0.957    1.000

In [47]:
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

In [55]:
np.round(st.kendalltau(x,y),3)

array([0.719, 0.   ])

In [77]:
df = pd.read_csv('data_studentlist.csv',header='infer')
df.head()

name gender  age  grade absence bloodtype  height  weight
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

In [79]:
x = df.height
y = df.weight

In [91]:
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [87]:
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z),'high':np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [89]:
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z),'high':np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}